### ISSUE TITLE
Resume link is broken

### ISSUE THREAD

**Issue by pmdarrow** [bozdoz/bozdoz.com#10]
This link is broken:

<img width="681" alt="screen shot 2018-04-06 at 8 35 23 pm" src="https://user-images.githubusercontent.com/586800/38448365-1a37cb30-39da-11e8-8b13-ea870d0cf06b.png">

<img width="682" alt="screen shot 2018-04-06 at 8 36 44 pm" src="https://user-images.githubusercontent.com/586800/38448395-3e6dae66-39da-11e8-890f-f411877bf36c.png">

**Comment by bozdoz** [comment]
Guess I should add that page to the test coverage
